name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, run and push
        run: |
          docker build . --tag ghcr.io/edufdezsoy/hello-world-ghcr-test:latest
          docker run ghcr.io/edufdezsoy/hello-world-ghcr-test:latest
          docker push ghcr.io/edufdezsoy/hello-world-ghcr-test:latest
